import { GuestFooter, GuestHeader } from "@/components/navigation";
import { Separator } from "@/components/separator";
import { env } from "@packages/env";
import { Toaster } from "@packages/ui";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: env.NEXT_PUBLIC_BLOG_APP_NAME || "Next.js App",
  description: "Generated by create next app",
};

export default function SSGLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <GuestHeader />
      {children}
      <Separator />
      <GuestFooter />
      <Toaster richColors closeButton />
    </>
  );
}
