import { options } from "@/lib/server";
import { AuthProvider, ToastProvider } from "@/provider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_SITE_NAME || "Next.js App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  return (
    <AuthProvider session={session}>
      <ToastProvider defaultLimit={3}>{children}</ToastProvider>
    </AuthProvider>
  );
}
