import { env } from "@/env";
import { TRPCReactProvider } from "@/trpc/react";
import { Header, Separator, ThemeProvider, Toaster } from "@packages/ui";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: env.NEXT_PUBLIC_APP_NAME || "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TRPCReactProvider>
            <Header name="blog" />
            {children}
            <Separator />
            <Toaster richColors closeButton />
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
