import { GuestFooter, GuestHeader } from "@/components/navigation";
import { Separator } from "@/components/separator";
import { ThemeProvider } from "@/provider";
import { env } from "@packages/env";
import { Toaster } from "@packages/ui";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: env.NEXT_PUBLIC_BLOG_APP_NAME || "Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <GuestHeader />
          {children}
          <Separator />
          <GuestFooter />
          <Toaster richColors closeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
