import { ReactNode } from "react";

import { Button } from "@/components/ui/button";
import { ResizableHandle, ResizablePanel } from "@/components/ui/resizable";
import { ScrollArea } from "@/components/ui/scroll-area";
import { defaultLayout } from "@/lib/config";
import { prisma } from "@/lib/server";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { TiPlus } from "react-icons/ti";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_SITE_NAME || "Next.js App",
  description: "Generated by create next app",
};

export default async function StudioStackLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const stacks = await prisma.tech.findMany({
    select: {
      id: true,
      name: true,
      logo: true,
      createdAt: true,
    },
  });
  return (
    <>
      <ResizableHandle withHandle />
      <ResizablePanel defaultSize={defaultLayout[1]} className="">
        <div className="flex items-center justify-between p-4 border-b">
          <h2 className="text-2xl font-semibold">Stacks</h2>
          <Link href="/studio/stacks/new">
            <Button role="button">
              <TiPlus className="h-4 w-4" />
              <span className="ml-2">New Stack</span>
            </Button>
          </Link>
        </div>
        <ScrollArea className="h-[calc(83vh)] p-2">
          {stacks.map((stack) => (
            <div
              key={stack.id}
              className="hover:bg-neutral-700 flex items-center justify-between mb-4 p-2 rounded-md "
            >
              <Link href={"/studio/stacks/" + stack.id} key={stack.id}>
                <div className="flex items-center gap-4">
                  <div className="h-16 w-16 relative">
                    <Image
                      src={stack.logo || "https://via.placeholder.com/100"}
                      alt={stack.name}
                      fill
                      className="object-cover rounded-md"
                      sizes="100px"
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <h3 className="text-lg font-medium">{stack.name}</h3>
                    <time dateTime={stack.createdAt.toISOString()}>
                      {stack.createdAt.toDateString()}
                    </time>
                  </div>
                </div>
              </Link>
            </div>
          ))}
        </ScrollArea>
      </ResizablePanel>
      <ResizableHandle withHandle />
      {children}
    </>
  );
}
